import {MigrationInterface, QueryRunner} from "typeorm";

export class Migration1651497181527 implements MigrationInterface {
    name = 'Migration1651497181527'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` DROP FOREIGN KEY \`FK_53eea3896c04e022538ceaac65d\``);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` DROP FOREIGN KEY \`FK_906ec9978aa4cbc16d635405f1d\``);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_category\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`company_category\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`licence\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`licence\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`work_field\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`work_field\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` DROP FOREIGN KEY \`FK_9633c0cb30e59b3c11e773a20a8\``);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`company_category_id\` \`company_category_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`operation_type\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`operation_type\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`operation\` DROP FOREIGN KEY \`FK_a3ae8f466f04ad4e8de987db807\``);
        await queryRunner.query(`ALTER TABLE \`operation\` DROP FOREIGN KEY \`FK_4997881e8971fefcd8ebbb17227\``);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`operation_type_id\` \`operation_type_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`client_operation_type_id\` \`client_operation_type_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`file\` DROP FOREIGN KEY \`FK_3dd35116e8ddce4c9364cd6cf0d\``);
        await queryRunner.query(`ALTER TABLE \`file\` DROP FOREIGN KEY \`FK_516f1cf15166fd07b732b4b6ab0\``);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`operation_id\` \`operation_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`birth_date\` \`birth_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`birth_place\` \`birth_place\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`user_type\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`user_type\` enum ('admin', 'system engineer', 'user') NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`verification_token\` \`verification_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`agent\` DROP FOREIGN KEY \`FK_031462988904ed291dd85171a86\``);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`career\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`career\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_role\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_role\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD CONSTRAINT \`FK_9633c0cb30e59b3c11e773a20a8\` FOREIGN KEY (\`company_category_id\`) REFERENCES \`company_category\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`operation\` ADD CONSTRAINT \`FK_a3ae8f466f04ad4e8de987db807\` FOREIGN KEY (\`operation_type_id\`) REFERENCES \`operation_type\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`operation\` ADD CONSTRAINT \`FK_4997881e8971fefcd8ebbb17227\` FOREIGN KEY (\`client_operation_type_id\`) REFERENCES \`client_operation_type\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`file\` ADD CONSTRAINT \`FK_3dd35116e8ddce4c9364cd6cf0d\` FOREIGN KEY (\`operation_id\`) REFERENCES \`operation\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`file\` ADD CONSTRAINT \`FK_516f1cf15166fd07b732b4b6ab0\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agent\` ADD CONSTRAINT \`FK_031462988904ed291dd85171a86\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` ADD CONSTRAINT \`FK_53eea3896c04e022538ceaac65d\` FOREIGN KEY (\`workFieldId\`) REFERENCES \`work_field\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` ADD CONSTRAINT \`FK_906ec9978aa4cbc16d635405f1d\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` DROP FOREIGN KEY \`FK_906ec9978aa4cbc16d635405f1d\``);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` DROP FOREIGN KEY \`FK_53eea3896c04e022538ceaac65d\``);
        await queryRunner.query(`ALTER TABLE \`agent\` DROP FOREIGN KEY \`FK_031462988904ed291dd85171a86\``);
        await queryRunner.query(`ALTER TABLE \`file\` DROP FOREIGN KEY \`FK_516f1cf15166fd07b732b4b6ab0\``);
        await queryRunner.query(`ALTER TABLE \`file\` DROP FOREIGN KEY \`FK_3dd35116e8ddce4c9364cd6cf0d\``);
        await queryRunner.query(`ALTER TABLE \`operation\` DROP FOREIGN KEY \`FK_4997881e8971fefcd8ebbb17227\``);
        await queryRunner.query(`ALTER TABLE \`operation\` DROP FOREIGN KEY \`FK_a3ae8f466f04ad4e8de987db807\``);
        await queryRunner.query(`ALTER TABLE \`company\` DROP FOREIGN KEY \`FK_9633c0cb30e59b3c11e773a20a8\``);
        await queryRunner.query(`ALTER TABLE \`agent_role\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent_role\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`career\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`career\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent\` ADD CONSTRAINT \`FK_031462988904ed291dd85171a86\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`verification_token\` \`verification_token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`user_type\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`user_type\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`birth_place\` \`birth_place\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`birth_date\` \`birth_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`operation_id\` \`operation_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`file\` ADD CONSTRAINT \`FK_516f1cf15166fd07b732b4b6ab0\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`file\` ADD CONSTRAINT \`FK_3dd35116e8ddce4c9364cd6cf0d\` FOREIGN KEY (\`operation_id\`) REFERENCES \`operation\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`client_operation_type_id\` \`client_operation_type_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`operation_type_id\` \`operation_type_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation\` ADD CONSTRAINT \`FK_4997881e8971fefcd8ebbb17227\` FOREIGN KEY (\`client_operation_type_id\`) REFERENCES \`client_operation_type\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`operation\` ADD CONSTRAINT \`FK_a3ae8f466f04ad4e8de987db807\` FOREIGN KEY (\`operation_type_id\`) REFERENCES \`operation_type\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation_type\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation_type\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`company_category_id\` \`company_category_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD CONSTRAINT \`FK_9633c0cb30e59b3c11e773a20a8\` FOREIGN KEY (\`company_category_id\`) REFERENCES \`company_category\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_field\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_field\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`licence\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`licence\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_category\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_category\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` ADD CONSTRAINT \`FK_906ec9978aa4cbc16d635405f1d\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` ADD CONSTRAINT \`FK_53eea3896c04e022538ceaac65d\` FOREIGN KEY (\`workFieldId\`) REFERENCES \`work_field\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
    }

}
