import {MigrationInterface, QueryRunner} from "typeorm";

export class Migration1651349782416 implements MigrationInterface {
    name = 'Migration1651349782416'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` DROP FOREIGN KEY \`FK_53eea3896c04e022538ceaac65d\``);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` DROP FOREIGN KEY \`FK_906ec9978aa4cbc16d635405f1d\``);
        await queryRunner.query(`ALTER TABLE \`account\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`account\` ADD UNIQUE INDEX \`IDX_d4ab593c192bae26a6cf638633\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`company_category\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`company_category\` ADD UNIQUE INDEX \`IDX_bbb4e6dcc98c00cd7fb9f28d94\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`licence\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`licence\` ADD UNIQUE INDEX \`IDX_05890209b13af2564e2ab3b564\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`work_field\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`work_field\` ADD UNIQUE INDEX \`IDX_670d7d064a676f35c6c7faeb15\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD UNIQUE INDEX \`IDX_47216baa0f0c8ebc6ee5a74989\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`operation_type\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`operation_type\` ADD UNIQUE INDEX \`IDX_65fd64c07b649cef6dfefd9c3f\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` ADD UNIQUE INDEX \`IDX_96b3c6f1731f4eb95dca91f97f\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`operation\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`operation\` ADD UNIQUE INDEX \`IDX_c863962043178f74d4e0498431\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`file\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`file\` ADD UNIQUE INDEX \`IDX_83b609bac13972b5378e424790\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`created_at\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`creator_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`agent\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`agent\` ADD UNIQUE INDEX \`IDX_6afd1141ee4df210692f0d025f\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`career\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`career\` ADD UNIQUE INDEX \`IDX_8c1fd7d632e10d5c633543272b\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`agent_role\` ADD \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_role\` ADD UNIQUE INDEX \`IDX_45190e39b97ac612aa6b06efc5\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_category\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`company_category\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`licence\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`licence\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`work_field\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`work_field\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` DROP FOREIGN KEY \`FK_9633c0cb30e59b3c11e773a20a8\``);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`company_category_id\` \`company_category_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`operation_type\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`operation_type\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`operation\` DROP FOREIGN KEY \`FK_a3ae8f466f04ad4e8de987db807\``);
        await queryRunner.query(`ALTER TABLE \`operation\` DROP FOREIGN KEY \`FK_4997881e8971fefcd8ebbb17227\``);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`operation_type_id\` \`operation_type_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`client_operation_type_id\` \`client_operation_type_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`file\` DROP FOREIGN KEY \`FK_3dd35116e8ddce4c9364cd6cf0d\``);
        await queryRunner.query(`ALTER TABLE \`file\` DROP FOREIGN KEY \`FK_516f1cf15166fd07b732b4b6ab0\``);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`operation_id\` \`operation_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`slug\` \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`birth_date\` \`birth_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`birth_place\` \`birth_place\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`verification_token\` \`verification_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`agent\` DROP FOREIGN KEY \`FK_031462988904ed291dd85171a86\``);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`career\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`career\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_role\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`agent_role\` CHANGE \`updater_id\` \`updater_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD CONSTRAINT \`FK_9633c0cb30e59b3c11e773a20a8\` FOREIGN KEY (\`company_category_id\`) REFERENCES \`company_category\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`operation\` ADD CONSTRAINT \`FK_a3ae8f466f04ad4e8de987db807\` FOREIGN KEY (\`operation_type_id\`) REFERENCES \`operation_type\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`operation\` ADD CONSTRAINT \`FK_4997881e8971fefcd8ebbb17227\` FOREIGN KEY (\`client_operation_type_id\`) REFERENCES \`client_operation_type\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`file\` ADD CONSTRAINT \`FK_3dd35116e8ddce4c9364cd6cf0d\` FOREIGN KEY (\`operation_id\`) REFERENCES \`operation\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`file\` ADD CONSTRAINT \`FK_516f1cf15166fd07b732b4b6ab0\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agent\` ADD CONSTRAINT \`FK_031462988904ed291dd85171a86\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` ADD CONSTRAINT \`FK_53eea3896c04e022538ceaac65d\` FOREIGN KEY (\`workFieldId\`) REFERENCES \`work_field\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` ADD CONSTRAINT \`FK_906ec9978aa4cbc16d635405f1d\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` DROP FOREIGN KEY \`FK_906ec9978aa4cbc16d635405f1d\``);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` DROP FOREIGN KEY \`FK_53eea3896c04e022538ceaac65d\``);
        await queryRunner.query(`ALTER TABLE \`agent\` DROP FOREIGN KEY \`FK_031462988904ed291dd85171a86\``);
        await queryRunner.query(`ALTER TABLE \`file\` DROP FOREIGN KEY \`FK_516f1cf15166fd07b732b4b6ab0\``);
        await queryRunner.query(`ALTER TABLE \`file\` DROP FOREIGN KEY \`FK_3dd35116e8ddce4c9364cd6cf0d\``);
        await queryRunner.query(`ALTER TABLE \`operation\` DROP FOREIGN KEY \`FK_4997881e8971fefcd8ebbb17227\``);
        await queryRunner.query(`ALTER TABLE \`operation\` DROP FOREIGN KEY \`FK_a3ae8f466f04ad4e8de987db807\``);
        await queryRunner.query(`ALTER TABLE \`company\` DROP FOREIGN KEY \`FK_9633c0cb30e59b3c11e773a20a8\``);
        await queryRunner.query(`ALTER TABLE \`agent_role\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent_role\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`career\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`career\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent\` ADD CONSTRAINT \`FK_031462988904ed291dd85171a86\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`verification_token\` \`verification_token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`birth_place\` \`birth_place\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`birth_date\` \`birth_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`slug\` \`slug\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`user_id\` \`user_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`operation_id\` \`operation_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`file\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`file\` ADD CONSTRAINT \`FK_516f1cf15166fd07b732b4b6ab0\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`file\` ADD CONSTRAINT \`FK_3dd35116e8ddce4c9364cd6cf0d\` FOREIGN KEY (\`operation_id\`) REFERENCES \`operation\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`client_operation_type_id\` \`client_operation_type_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`operation_type_id\` \`operation_type_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation\` ADD CONSTRAINT \`FK_4997881e8971fefcd8ebbb17227\` FOREIGN KEY (\`client_operation_type_id\`) REFERENCES \`client_operation_type\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`operation\` ADD CONSTRAINT \`FK_a3ae8f466f04ad4e8de987db807\` FOREIGN KEY (\`operation_type_id\`) REFERENCES \`operation_type\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation_type\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`operation_type\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`company_category_id\` \`company_category_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD CONSTRAINT \`FK_9633c0cb30e59b3c11e773a20a8\` FOREIGN KEY (\`company_category_id\`) REFERENCES \`company_category\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_field\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`work_field\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`licence\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`licence\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_category\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_category\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`updater_id\` \`updater_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`account\` CHANGE \`updated_at\` \`updated_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`agent_role\` DROP INDEX \`IDX_45190e39b97ac612aa6b06efc5\``);
        await queryRunner.query(`ALTER TABLE \`agent_role\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`career\` DROP INDEX \`IDX_8c1fd7d632e10d5c633543272b\``);
        await queryRunner.query(`ALTER TABLE \`career\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`agent\` DROP INDEX \`IDX_6afd1141ee4df210692f0d025f\``);
        await queryRunner.query(`ALTER TABLE \`agent\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`updater_id\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`creator_id\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`file\` DROP INDEX \`IDX_83b609bac13972b5378e424790\``);
        await queryRunner.query(`ALTER TABLE \`file\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`operation\` DROP INDEX \`IDX_c863962043178f74d4e0498431\``);
        await queryRunner.query(`ALTER TABLE \`operation\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` DROP INDEX \`IDX_96b3c6f1731f4eb95dca91f97f\``);
        await queryRunner.query(`ALTER TABLE \`client_operation_type\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`operation_type\` DROP INDEX \`IDX_65fd64c07b649cef6dfefd9c3f\``);
        await queryRunner.query(`ALTER TABLE \`operation_type\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`company\` DROP INDEX \`IDX_47216baa0f0c8ebc6ee5a74989\``);
        await queryRunner.query(`ALTER TABLE \`company\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`work_field\` DROP INDEX \`IDX_670d7d064a676f35c6c7faeb15\``);
        await queryRunner.query(`ALTER TABLE \`work_field\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`licence\` DROP INDEX \`IDX_05890209b13af2564e2ab3b564\``);
        await queryRunner.query(`ALTER TABLE \`licence\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`company_category\` DROP INDEX \`IDX_bbb4e6dcc98c00cd7fb9f28d94\``);
        await queryRunner.query(`ALTER TABLE \`company_category\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`account\` DROP INDEX \`IDX_d4ab593c192bae26a6cf638633\``);
        await queryRunner.query(`ALTER TABLE \`account\` DROP COLUMN \`slug\``);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` ADD CONSTRAINT \`FK_906ec9978aa4cbc16d635405f1d\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`companies_workfields\` ADD CONSTRAINT \`FK_53eea3896c04e022538ceaac65d\` FOREIGN KEY (\`workFieldId\`) REFERENCES \`work_field\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
    }

}
